-- Migration number: 0002 	 2025-11-09T00:00:00.000Z
CREATE TABLE IF NOT EXISTS SESSIONS_SCHEDULE_HISTORY (
    POOL_ID VARCHAR(30),
    UPDATED_AT DATETIME,
    SESSION_DATE VARCHAR(20) NOT NULL,
    SESSION_TIME VARCHAR(10) NOT NULL,
    SESSION_DATETIME DATETIME NOT NULL,
    SESSION_TITLE VARCHAR(255) NOT NULL,
    SESSION_SIDE TEXT CHECK(SESSION_SIDE IN ('LEFT', 'RIGHT')) NOT NULL,
    AVAILABLE_SPOTS INTEGER NOT NULL,
    AREA VARCHAR(100)
);
